spring.application.name=graph

spring.datasource.url=jdbc:postgresql://localhost:5433/palletron
spring.datasource.username=palletron_app
spring.datasource.password=PalletronApp_2026_Local
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect